import Head from 'next/head'
import { useState } from 'react';
import Tables from './components/Tables';


export default function Home() {

  const [ingr,setIngr] = useState("");
  const [dish,setDish] = useState("");
  const [kcals,setKcals] = useState("");
  const [currentFood,setCurrentFood] = useState({name:"",dish:"",kcals:""});
  const handleSubmit = (e) =>{
    e.preventDefault();
    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Host': 'edamam-food-and-grocery-database.p.rapidapi.com',
        'X-RapidAPI-Key': 'ed891157f5mshc9042211f64f080p1bbbf9jsnedd6101045bb'
      }
    };
    
    fetch('https://edamam-food-and-grocery-database.p.rapidapi.com/parser?ingr='+ingr, options)
      .then(response => response.json())
      .then(response => setKcals(response.parsed[0].food.nutrients.ENERC_KCAL)).then(setCurrentFood({name:ingr,dish:dish,kcals:kcals}))
      .catch(err => console.error(err));
  }
  return (
    <div>
      <Head>
        <title>Calorie intake counter</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <nav>nav</nav>
    <main>
    <Tables currentFood={currentFood}/>
    </main>
    <form onSubmit={handleSubmit}>
      <h3>Add something</h3>
      <label htmlFor="food">Food</label>
      <input type="text" name="food" id="food" onChange={e=>setIngr(e.target.value)}/>
      {/*  */}
      <input type="radio" name="dish" id="Breakfast" value="breakfast" onChange={e=>{setDish(e.target.value)}}/>
      <label htmlFor="breakfast">Breakfast</label>
      <input type="radio" name="dish" id="Lunch" value="lunch" onChange={e=>{setDish(e.target.value)}}/>
      <label htmlFor="Lunch">Lunch</label>
      <input type="radio" name="dish" id="Dinner" value="dinner" onChange={e=>{setDish(e.target.value)}}/>
      <label htmlFor="Dinner">Dinner</label>
      <input type="radio" name="dish" id="Snacks" value="snacks" onChange={e=>{setDish(e.target.value)}}/>
      <label htmlFor="Snacks">Snacks</label>

      <button type="submit">submit</button>
    </form>
    </div>
  )
}
