import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext,} from "react";

import { useAuth } from "../firebase";
import AvatarImage from "../public/mm.png";
import { userContext } from "../src/userContext";

function MyProfile() {
  const { user, dailyRequirement, newWeight } = useAuth();

  const { lifts, powerliftingScore } = useContext(userContext);


  return (
    <div className="w-screen h-screen bg-myBlue ">
      <Head>
        <title>Calorie intake counter</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <span className="text-white absolute top-2 left-2 cursor-pointer">
          go back to the main page
        </span>
      </Link>
      <div className="bg-white w-5/6 h-96 left-1/2 -translate-x-1/2 -translate-y-1/2 absolute top-1/2">
        <div className="grid grid-cols-4 p-5 h-full">
          <div className="flex justify-center items-center">
            <Image src={AvatarImage} alt="avatar" />
          </div>
          <div className="text-center flex text-lg font-semibold  flex-col justify-around">
            <h2>{user?.email}</h2>
            <div className="flex gap-5 flex-col items-center">
              <h2>Your current weight: {newWeight} kg</h2>
              <h2>Your daily cal-requirement: {dailyRequirement}</h2>
              <Link href="/setnewrequirements">
                <span className="w-20 text-white p-1 font-bold shadow bg-myBlue focus:shadow-outline hover:text-myLightBlue cursor-pointer transition-all ease-out rounded-sm">
                  SET IT
                </span>
              </Link>
            </div>
          </div>
          <div className="text-lg flex flex-col justify-around items-center col-span-2 text-center font-semibold">
            <h1 className="text-xl">YOUR LIFTS</h1>
            <div>
              <h2>Bench press: {lifts.bench}</h2>
      
            </div>

            <h2>Deadlift: {lifts.deadlift}</h2>

            <h2>Squat: {lifts.squat}</h2>
            <h2>Powerlifting score: {powerliftingScore}</h2>
            <Link href="/setNewLifts">
              <span className="w-20 text-white p-1 font-bold shadow bg-myBlue focus:shadow-outline hover:text-myLightBlue cursor-pointer transition-all ease-out rounded-sm">
                SET IT
              </span>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyProfile;
