
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {useAuth} from '../firebase'
import AvatarImage from '../public/mm.png'
function MyProfile() {
  const {currentUser,dailyRequirement} = useAuth();




  return (
    <div className="w-screen h-screen bg-myDarkBlue ">
      <Head>
        <title>Calorie intake counter</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <span className="text-white absolute top-2 left-2 cursor-pointer">
          go back to the main page
        </span>
      </Link>
      <div className="bg-white w-5/6 h-96 left-1/2 -translate-x-1/2 -translate-y-1/2 absolute top-1/2">
        <div className="grid grid-cols-4 p-5 h-full">
          <div className="flex justify-center items-center">
            <Image src={AvatarImage} alt="avatar"/>
          </div>
          <div className="col-span-3 flex text-lg font-semibold flex-col justify-around">
            <h2>{currentUser?.email}</h2>
            <div className="flex gap-5 items-center">
            <h2>Your daily requirement: {dailyRequirement}</h2>
          <Link href="/setnewrequirements"><span className=" text-white p-1 font-bold shadow bg-myDarkBlue focus:shadow-outline hover:text-myLightBlue cursor-pointer transition-all ease-out rounded-sm">SET IT</span></Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyProfile;
