import Head from "next/head";
import Link from "next/link";
import React from "react";

function SetNewRequirements() {
  return (
    <div className="w-screen h-screen bg-myDarkBlue ">
      <Head>
        <title>Calorie intake counter</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/myprofile">
        <span className="text-white absolute top-2 left-2 cursor-pointer">
          go back to my profile
        </span>
      </Link>
      <div className="bg-white w-5/6 h-96 left-1/2 -translate-x-1/2 -translate-y-1/2 absolute top-1/2">
        <form className="h-full justify-around flex flex-col items-center">
          <fieldset className="flex gap-5">
            <h2>Age:</h2>
            <input type="number" name="Age" id="Age" />
            <label htmlFor="Age">Years</label>
          </fieldset>
          <fieldset className="flex gap-5">
            <h2>Sex:</h2>
            <div>
              <input type="radio" name="Sex" id="Male" value="Male" />
              <label htmlFor="Male"> Male</label>
            </div>
            <div>
              <input type="radio" name="Sex" id="Female" value="Female" />
              <label htmlFor="Female"> Female</label>
            </div>
          </fieldset>
          <fieldset className="flex gap-5">
            <h2>Weight:</h2>
            <input type="number" name="Weight" id="Weight" />
            <label htmlFor="Weight">kg</label>
          </fieldset>
<fieldset className="flex gap-5">
            <h2>Activity:</h2>
            <select id="Activity" name="Activity">
    <option value="none">No exercise and non physical work</option>
    <option value="light">1-3 training session per weak</option>
    <option value="hight">4-6 training session per week</option>
    <option value="extreme">multiple training sessions, or physical job</option>
  </select>
</fieldset>

        </form>
      </div>
    </div>
  );
}

export default SetNewRequirements;
