import React, { useRef, useState, useEffect, useContext } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { signin, useAuth } from "../firebase";
import Head from 'next/head'
function SignIn() {
  const Router = useRouter();
  const emailRef = useRef();
  const {user} = useAuth();
  const passwordRef = useRef();
  const [loading, setLoading] = useState(false);
  const handleSignIn = async (e) => {
    setLoading(true);
    e.preventDefault();
    try {
      await signin(emailRef.current.value, passwordRef.current.value);

    } catch (err) {
      alert(err);
    }

    setLoading(false);
  };

  useEffect(() => {
    if (user) {
      console.log("jest user pushuje do glownej")
      console.log(user)
      Router.push("/");}
  }, [user]);

  return (
    <div className="max-w-screen flex items-center justify-center h-screen bgGradient text-white">
           <Head>
        <title>Calorie intake counter</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <span className="absolute top-2 left-2 cursor-pointer">
          go back to the main page
        </span>
      </Link>
      <div className="flex flex-col bg-white text-gray-900 justify-between w-124 h-96 text-center font-semibold text-lg border-2 border-white shadow-xl p-4 rounded-md">
        <form className="flex flex-col" onSubmit={handleSignIn}>
          <h2 className="py-5">Sign In</h2>
          <div className="py-2 flex justify-between">
            <label htmlFor="email">e-mail: </label>
            <input
              className="text-black border"
              ref={emailRef}
              type="email"
              name="email"
              id="email"
            />
          </div>
          <div className="py-2 flex justify-between">
            <label htmlFor="email" className="mr-1">
              password:{" "}
            </label>
            <input
              className="text-black border"
              ref={passwordRef}
              type="password"
              name="passwd"
              id="passwd"
            />
          </div>

          <button
            disabled={loading}
            type="submit"
            className=" px-4 py-2 mt-16 mx-auto border rounded-md shadow border-myBlue  font-bold  bg-white focus:shadow-outline hover:bg-myLightBlue transition-all ease-out"
          >
            SIGN IN
          </button>
        </form>
        <Link href="/signup">
          <span className="hover:text-myLightBlue cursor-pointer transition-all ease-out">
            i don&apos;t have an account
          </span>
        </Link>
      </div>
    </div>
  );
}

export default SignIn;
